(define (unbound? expr (tagged-list? expr 'unbound)))
(define (unbind-variable expr env) (make-unbound! (cadr expr) env))
(define (make-unbound! var env)
  (define (env-loop env)
    (define (scan vars vals pre-vars pre-vals)
      (cond ((null? vars)
             (error "Unbound variable -- UNBOUND!" var))
            ((eq? var (car vars))
			 (set-car! env (cons (append pre-vars (cdr vars)) (append pre-vals (cdr vals)))))
            (else (scan (cdr vars)
						(cdr vals)
						(cons (car vars) pre-vars)
						(cons (car vals) pre-vals)))))
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- UNBOUND!" var)
        (let ((frame (first-frame env)))
          (scan (frame-variables frame)
                (frame-values frame)
				'()
				'()))))
  (env-loop env))
(define (eval-unbound expr env)
  (make-unbound! (cadr expr) env))
