(define (lookup-variable-value var env)
  (define (env-loop env)
    (define (scan vars vals)
      (cond ((null? vars)
             (env-loop (enclosing-environment env)))
            ((eq? var (car vars))
			 (if (eq? '*unassigned* (car vals))
				 (error "Unassigend variable" var)
				 (car vals)))
            (else (scan (cdr vars) (cdr vals)))))
    (if (eq? env the-empty-environment)
        (error "Unbound variable" var)
        (let ((frame (first-frame env)))
          (scan (frame-variables frame)
                (frame-values frame)))))
  (env-loop env))

(define (make-lambda parameters body)
  (cons 'lambda (cons parameters body)))

(define (scan-out-defines procs)
  (let ((inits '()) (body '()))
	(define (scan-out-let-struct procs)
	  (cond ((not (null? procs))
			 (let ((first-proc (car procs)))
			   (cond ((pair? first-proc)
					  (cond ((eq? 'define (car first-proc))
							 (if (pair? (cadr first-proc)) ;; lambda
								 (begin (set! inits (cons (list (car (cadr first-proc)) '*unassigned*) inits))
										(set! body 
											  (cons (list 'set!
														  (car (cadr first-proc))
														  (make-lambda (cdr (cadr first-proc)) (cddr first-proc))) body)))
								 (begin (set! inits (cons (list (cadr first-proc) '*unassigned*) inits))
										(set! body (cons (list 'set! (cadr first-proc) (caddr first-proc)) body)))))
							(else (set! body (cons first-proc body)))))

					 (else (set! body (cons first-proc body))))
			   )
			 (scan-out-let-struct (cdr procs))))
	  (set! inits (reverse inits))
	  (set! body (reverse body))
	  )
	(scan-out-let-struct procs)
	(cons 'let (cons inits body))
	))

(display (scan-out-defines (list (list 'define (list 'm 'a 'b) (list '+ 'a 'b)) (list 'define 'n 100) (list 'define 'o 12312) 10000)))
(newline)
