(load "../lib/helper.scm")

(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item) (set-car! queue item))
(define (set-rear-ptr! queue item) (set-cdr! queue item))
(define (empty-queue? queue) (null? (front-ptr queue)))
(define (make-queue) (cons '() '()))

(define (front-queue queue)
  (if (empty-queue? queue)
      (error "FRONT called with an empty queue" queue)
      (car (front-ptr queue))))

(define (insert-queue! queue item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? queue)
           (set-front-ptr! queue new-pair)
           (set-rear-ptr! queue new-pair)
           queue)
          (else
           (set-cdr! (rear-ptr queue) new-pair)
           (set-rear-ptr! queue new-pair)
           queue))))

(define (delete-queue! queue)
  (cond ((empty-queue? queue)
         (error "DELETE! called with an empty queue" queue))
        (else
         (begin (set-front-ptr! queue (cdr (front-ptr queue)))
				(if (empty-queue? queue) (set-rear-ptr! queue '())))
		 queue)))

(define q (make-queue))
(insert-queue! q 'a)
(p q)
(insert-queue! q 'b)
(p q)
(insert-queue! q 'c)
(p q)
(insert-queue! q 'd)
(p q)
(insert-queue! q 'e)
(p q)
(p "try to del")
(delete-queue! q)
(delete-queue! q)
(delete-queue! q)
(delete-queue! q)
(delete-queue! q)
(p q)
(insert-queue! q 'a)
(p q)
(insert-queue! q 'b)
(p q)
(insert-queue! q 'c)
(p q)
